Connect server to values page
Project-Reclass/toynet-react pull request #63
Opened 2020-11-11 02:54 UTC by SYChJung

Checkout the [Engineer Workflow Doc](https://docs.google.com/presentation/d/1pdzuHG-yO7_qW6jiByaGTLztKZ6b72lBNqSdNT5WZQ8/edit) to make sure you're contributing correctly! :)

**[Tickets](https://trello.com/b/dYOQKJGv/reclass)** 
Trello Ticket: https://trello.com/c/O12d8SWT/386-connect-server-to-values-page
Additional Notes:

**[Dependencies](https://docs.google.com/document/d/1CM6OA2nlhI3DHnHdDEgySukx_tZ_wsG-C2YgraZRvJA/edit#heading=h.czpk4cbi7z4g)**

**[Explain Impact on DB](https://docs.google.com/document/d/1CM6OA2nlhI3DHnHdDEgySukx_tZ_wsG-C2YgraZRvJA/edit#heading=h.285lgcs4z84o)**

**[Testing](https://docs.google.com/document/d/1CM6OA2nlhI3DHnHdDEgySukx_tZ_wsG-C2YgraZRvJA/edit#heading=h.rs692kr58cf8)**

How did you test this? List of actions & expected behavior with helpful screenshots for reviewer:

If this change is performance related, please document what tests were / should be done to verify improvement:

2020-11-14 20:00 UTC, brandontiqui commented on src/ModuleList/Value/Value.tsx
> +`;
Can you make a styled.ts file and place these styled components there?  Then import them back into the Value component.

2020-11-14 20:13 UTC, brandontiqui requested changes
Nice work!  Let me know if you have questions about moving the styled components into a separate file and importing them back into the Value component.

2020-11-14 20:13 UTC, brandontiqui commented on src/ModuleList/Value/Value.tsx
> +
Can you make a styled.ts file and place these styled components there?  Then import them back into the Value component.

2020-11-16 01:21 UTC, scottjr632 approved these changes
Really good work John!! If you could just make the changes that @brandontiqui requested or reply back to why you think that those styled-components should stay in that one file before merging! Thanks!!

2020-11-16 05:02 UTC, brandontiqui approved these changes

2020-11-16 05:06 UTC, merged